import "./globals.css";
import Link from "next/link";
import {Orbitron} from 'next/font/google'

const orbitronFont = Orbitron({
  variable:"--font-orbitron",
  subsets:['latin'],
  weight:['400','600']
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={`${orbitronFont.variable}`}>
        <header >
          <h4>EXERCÍCIO 3 - CATÁLOGO DE ESPAÇONAVES</h4>
          <div className="router-links">
            <Link href={'/'}>Ínicio</Link>
            <Link href={'/espaconaves'}>Espaçonaves</Link>
            <Link href={'/categorias'}>Categorias</Link>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
